services:
  app_facilities_ch:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-clickhouse:v1.0.3
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      CLICKHOUSE_PASSWORD: $APP_FACILITIES_CH_CLICKHOUSE_PASSWORD
      CLICKHOUSE_URL: $APP_FACILITIES_CH_CLICKHOUSE_URL
      CLICKHOUSE_USERNAME: $APP_FACILITIES_CH_CLICKHOUSE_USERNAME
      HASURA_SERVICE_TOKEN_SECRET: $APP_FACILITIES_CH_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_FACILITIES_CH_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_FACILITIES_CH_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "6143"
        protocol: tcp
