services:
  personnel_personnel_pg:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.personnel_pg
    environment:
      CONNECTION_URI: $PERSONNEL_PERSONNEL_PG_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $PERSONNEL_PERSONNEL_PG_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $PERSONNEL_PERSONNEL_PG_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PERSONNEL_PERSONNEL_PG_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8121:8080
