services:
  clients_clients_mongo:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.clients_mongo
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $CLIENTS_CLIENTS_MONGO_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $CLIENTS_CLIENTS_MONGO_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $CLIENTS_CLIENTS_MONGO_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CLIENTS_CLIENTS_MONGO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7929:8080
